name: Review

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - v*

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  ##############################################################################
  ## BUILD AND REGISTER APPLICATION IMAGE
  ##############################################################################
  register:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@master
      with:
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}
        imageName: monsuivipsy/monsuivipsy-site

  ##############################################################################
  ## DEPLOY APPLICATION OVER KUBERNETES
  ##############################################################################
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [register]
    steps:

    - name: Use autodevops deployment
      uses: SocialGouv/actions/autodevops-helm-deploy@v1
      with:
        environment: "dev"
        token: ${{ secrets.GITHUB_TOKEN }}
        kubeconfig: ${{ secrets.SOCIALGOUV_KUBE_CONFIG_DEV }}
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
        rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
        socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
        imageName: monsuivipsy/monsuivipsy-site
